theme: jekyll-theme-hacker
title: Welcome to the Vis Major!
description: My personal blog about programming, AI, machine learning, computer graphics and much more. Feel free to bookmark this to keep an eye on my project updates!
